export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const OPEN_FORM_EDIT_PROJECT = 'OPEN_FORM_EDIT_PROJECT';
export const OPEN_FORM_CREATE_TASK = 'OPEN_FORM_CREATE_TASK';

export const OPEN_NOTIFI_FAIL = 'OPEN_NOTIFI_FAIL';
export const OPEN_NOTIFI_SUCCESS= 'OPEN_NOTIFI_SUCCESS';
export const RESET_NOTIFI = 'RESET_NOTIFI';


export const OPEN_NOTIFI_FAIL_LOGIN = 'OPEN_NOTIFI_FAIL_LOGIN';



