export const EDIT_DATA_USER ='EDIT_DATA_USER'
export const EDIT_DATA_USER_SAGA ='EDIT_DATA_USER_SAGA'

export const GET_USER_FORM_ID ='GET_USER_FORM_ID'
export const GET_USER_FORM_ID_SAGA ='GET_USER_FORM_ID_SAGA'

export const FILTER_USER ='FILTER_USER'
export const FILTER_USER_SAGA ='FILTER_USER_SAGA'